{{- /*
Secret Template for Veridactus Control Plane
*/ -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "veridactus-cp.fullname" . }}
  labels:
    {{- include "veridactus-cp.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-key: {{ required "config.adminKey is required" .Values.config.adminKey | quote }}
