{{- /*
Service Template for Veridactus Core
*/ -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "veridactus-core.fullname" . }}
  labels:
    {{- include "veridactus-core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "veridactus-core.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: core
